### ISSUE TITLE
Custom data 

### ISSUE THREAD

**Issue by VHornyi** [kevinlee09/VTO_3d#2]
Hello, the project looks very interesting. I have a couple of questions. Is it possible to run the model on my own obj files of clothing and a person? If so, would they require any special preprocessing? Also, if I understand correctly, the model works only with clothing for the upper body, is that right?

**Comment by kevinlee09** [comment]
Hi, if you use your own OBJ files, you need to align your clothing and body mesh roughly first. This repo can also work for the lower body when you use a lower clothing template.

**Comment by VHornyi** [comment]
Thank you for your response!
